global using System.Diagnostics;
global using System.Runtime.InteropServices;
global using System.Threading;
global using System;
global using System.Drawing;
global using WindowsInput;
global using Raylib_cs;
global using static Raylib_cs.Raylib;
global using System.Linq;
global using System.Collections.Generic;
global using System.Windows.Forms;
global using Color = System.Drawing.Color;
global using System.Threading.Tasks;
global using System.IO;
global using System.Text.Json;
global using System.Text.Json.Nodes;