name: Build & Upload

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
            ext: tar.gz
          - os: macos-latest
            rid: osx-x64
            ext: tar.gz
          - os: windows-latest
            rid: win-x64
            ext: zip

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Publish
        run: |
          if [ "${{ matrix.rid }}" = "win-x64" ]; then
            dotnet publish -c Release -r win-x64 \
              -p:PublishSingleFile=true \
              -p:IncludeNativeLibrariesForSelfExtract=true \
              --self-contained true -o out
          else
            dotnet publish -c Release -r ${{ matrix.rid }} \
              -p:PublishSingleFile=true \
              --self-contained true -o out
          fi

      - name: Package
        run: |
          cd out
          tag=${GITHUB_REF##*/}
          if [ "${{ matrix.ext }}" = "zip" ]; then
            zip -r ../MyApp-${tag}-${{ matrix.rid }}.zip *
          else
            tar -czf ../MyApp-${tag}-${{ matrix.rid }}.tar.gz *
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-${{ matrix.rid }}
          path: MyApp-${{ github.ref_name }}-${{ matrix.rid }}.*
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/**/*
